import os
os.chdir("C:\\Users\Marie\Documents\GRAD SCHOOL!\Riffell Lab Research\Theresa chemistry\Python")

import dicttocsv_csvtolist_v2 as conv

#read the full Kovats db dictionary back in from csv format
#this works fine when the csv has been generated by anything
#besides excel (which codes things in ANSI instead of utf-8).
#ie, open office, python
full_dict=conv.read_unicode_csv_to_dict("Kovats_db_NIST_dict.csv")

#read out just values so that can use these for a chem -> chem type
#dictionary
#make into a csv that is utf-8 encoded
chem_values = list(set(full_dict.values()))
conv.write_unicode_list_into_unicode_csv("chem_values_for_chem_class_dict.csv", chem_values)

#read in csv of Kovats db as lists to write back out together
Kovats_on_DB5 = conv.read_unicode_csv_col_to_list("VOC_Kovats_masterlist_140909_utf8.csv",0)
Compound_Name = conv.read_unicode_csv_col_to_list("VOC_Kovats_masterlist_140909_utf8.csv",1)
Source = conv.read_unicode_csv_col_to_list("VOC_Kovats_masterlist_140909_utf8.csv",2)
Data_From = conv.read_unicode_csv_col_to_list("VOC_Kovats_masterlist_140909_utf8.csv",3)


Compound_Name2=[] 
#replacing all synonyms single chem name from NIST
for item in Compound_Name:
	Compound_Name2.append(full_dict.get(item, item))
	
headers = [u'Kovats_on_DB5', u'Compound_Name', u'Source', u'Data_From']

conv.write_unicode_lists_to_csv_cols_head("Kovats_db_NISTsynonymconverted_140909_utf8.csv", headers, Kovats_on_DB5, Compound_Name2, Source, Data_From) 


